version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es01
    networks:
      - net-develop
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      #- discovery.seed_hosts=es02,es03
      #- cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - net-develop
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.5.2
    links:
     - "es01:elasticsearch"
    networks:
     - net-develop
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana    

volumes:
  elastic:
    external:
      name: elastic

networks:
  net-develop:
    external:
      name: net-develop