version: '3'
services: 
  kong:
    container_name: kong
    image: kong:1.1.0
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
    networks:
      - developer      
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_DATABASE=postgres
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=password
      - KONG_PG_HOST=postgres
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000 ssl

networks:
  developer:
    external:
      name: developer