version: '3'
services: 
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5  
    volumes:
      - D:\docker_mounted\mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    