version: '3'
services: 
  postgres:
    container_name: postgres
    image: postgres:9.6
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      restart_policy:
        condition: always
        max_attempts: 5
    networks:
      - developer      
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
volumes:
  pgdata:
    external:
      name: pgdata
networks:
  developer:
    external:
      name: developer     